also updated format binary to std. format

diff --git a/bin/format b/bin/format
--- a/bin/format
+++ b/bin/format
@@ -1,34 +1,17 @@
 #!/usr/bin/env zsh
+version=1.0.0
+name=$(basename $0)
+
+# make pipeable
 source "$(dirname $0)/pipeable"
 
-# functions
-help() {
-    cat <<EOL
-Usage: $0 [-h] [-o <format>] <datetime>
-Formats the given datetime to the given datetime
+# variables
+output=long
 
-<format> can either be 'short', 'long' or a format string as described in gdate
-
-When no <format> is chosen, the output defaults to 'long'
-EOL
-}
-
-extractParts() {
-    d=$(($td/86400))
-    h=$((($td-$d*86400)/3600))
-    m=$((($td-$d*86400-$h*3600)/60))
-    s=$(($td-$d*86400-$h*3600-$m*60))
-}
-
-concat() {
-    local d=$1; shift
-    echo -n "$1"; shift
-    printf "%s" "${@/#/$d}"
-}
-
-long() {
+# format functions
+format-long() {
     parts=()
-    extractParts "$@"
+    -extract-parts "$@"
     if [ "$d" -eq 1 ]; then
         echo "$d day"
         return 0
@@ -49,18 +32,17 @@ long() {
     fi
     if [ "$h" -eq 0 ]; then
         test "$tms" -ne 0 && sms="$s.$tms" || sms="$s"
-        if [ "$s" -eq 1 ]; then
+        if [ "$s" -eq 1 ] && [ "$s" = "$sms" ]; then
             parts+="$sms second"
-        elif [ "$s" -gt 1 ]; then
+        else
             parts+="$sms seconds"
         fi
     fi
-    concat ', ' $parts
+    -concat ', ' $parts
     echo ''
 }
-
-short() {
-    extractParts "$@"
+format-short() {
+    -extract-parts "$@"
     if [ "$td" -gt 86400 ]; then
         echo "${d}d ${h}h${m}m"
     elif [ "$td" -gt 3600 ]; then
@@ -71,22 +53,69 @@ short() {
         echo $s\"$tms
     fi
 }
+
+# functions
+-help() {
+    echo "Usage: $name [OPTION] <timestamp>"
+    echo "Formats the given datetime to the given datetime"
+    echo
+    echo '  -h, --help              Displays this help function'
+    echo "  -o, --output=FORMAT     Forces output format [default: $output]"
+    echo '  -v, --version           Displays the version number'
+    echo
+    echo "FORMAT can either be 'short', 'long' or a format string as described in gdate"
+}
+-extract-parts() {
+    d=$(($td/86400))
+    h=$((($td-$d*86400)/3600))
+    m=$((($td-$d*86400-$h*3600)/60))
+    s=$(($td-$d*86400-$h*3600-$m*60))
+}
+-concat() {
+    local d=$1; shift
+    echo -n "$1"; shift
+    printf "%s" "${@/#/$d}"
+}
+-error() {
+    err='Unknown error'
+    case "$1" in
+        args) err="Missing argument for $2";;
+        flag) err="Unknown argument $2";;
+    esac
+    echo ${RED}Error: $err${RESET_COLOR}; -help; exit 1
+}
+
 # read the options
-input=%s.%N
-output=long
-case "$1" in
-    -o) output="$2"; shift 2;;
-    -h) help; exit 1;;
-esac
-t=$(date -ud @${1:-0} +${input})
+set -- $(echo $@ | tr '=' ' ')
+while [ "${1:0:1}" = '-' ]; do
+    case "$1" in
+        -h|--help) -help; exit;;
+        -o|--output)
+            test -z "$2" && -error args "$1"
+            output="$2"
+            shift 2
+            ;;
+        -v|--version) echo $version; exit;;
+        *)
+            if [ "${#1}" -gt 2 ] && ! [ "${1:1:1}" = '-' ]; then
+                set -- -${1:1:1} -${1:2} ${@:2}
+            else
+                -error flag "$1"
+            fi
+            ;;
+    esac
+done
+
+# set time variables
+t=$(date -ud @${1:-0} +%s.%N)
 td=$(printf %d $t)
 tms=$(printf %03d $((($t-$td)*1000)) )
 
-
+# evaluate input into output
 if [ "$output" = 'short' ]; then
-    short $t
+    format-short $t
 elif [ "$output" = 'long' ]; then
-    long $t
+    format-long $t
 else
     date -u -d @$t +$output
 fi
